# Writes firmware/voting_with_sms/secrets.h from environment variables set by setup.bat.
# Values come from the environment so special characters in passwords never touch cmd quoting.
param([Parameter(Mandatory = $true)][string]$Out)

function Esc([string]$s) { return ($s -replace '\\', '\\' -replace '"', '\"') }

$phone = ($env:VS_PHONE -replace '\D', '')
if ($phone.Length -eq 10) { $phone = '91' + $phone }
if ($phone.Length -gt 0 -and $phone.Length -ne 12) {
    Write-Host "Warning: phone '$env:VS_PHONE' is not 10 digits (or 91 + 10). Check it in secrets.h." -ForegroundColor Yellow
}

$lines = @(
    '// Local secrets (git-ignored). Generated by setup.bat. See secrets.example.h.',
    '#pragma once',
    ('const char* WIFI_SSID = "{0}";' -f (Esc $env:VS_SSID)),
    ('const char* WIFI_PASS = "{0}";' -f (Esc $env:VS_WIFIPASS)),
    ('const char* ADMIN_USER = "{0}";' -f (Esc $env:VS_ADMIN)),
    ('const char* ADMIN_PASS = "{0}";' -f (Esc $env:VS_ADMINPASS)),
    ('const char* SMS_API_KEY = "{0}";' -f (Esc $env:VS_APIKEY)),
    ('const char* DEFAULT_ADMIN_PHONE = "{0}";' -f $phone)
)
[System.IO.File]::WriteAllLines($Out, $lines, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $Out"
